/*
1. Write a program to show the use of function templates.
2. Write a program to show the use of class templates.
3. Write a program to show the use of exception handling (try, throw, & catch).
4. Write a program to show the use of multiple catch statements.
5. Write a program to catch all the exception.
6. Write a program re-throwing an exception.
7. Write a program to catch specified exceptions only.
*/