/*
1. Write a program to write and read text in file.
2. Write a program to show the use of get () and put () functions.
3. Write a program working with multiple files in a single program.
4. Write a program to append some contents in existing file.
5. Write a program to show the use of seekg() function.
6. Write a program to show the use of write () and read () functions.
7. Write a program to copy contents from one file to another file. 
*/